#!/usr/bin/env python3
r"""Generate include/uocr/unicode_tables.h.

The DeepSeek BPE pre-tokenizer uses the HuggingFace `tokenizers` regex crate with
Unicode property classes (\p{L}, \p{M}, \p{N}, \p{P}, \p{S}).  We cannot use
std::regex for this, so we bake the Unicode general-category masks into a compact
sorted range table generated from Python's `unicodedata` (Unicode 16.0, matching
the regex crate used by tokenizers 0.22).

Bit layout: L=1, M=2, N=4, P=8, S=16.  Whitespace (`\s`, Unicode White_Space)
is stored as a separate range table.
"""

import os
import unicodedata

BIT = {"L": 1, "M": 2, "N": 4, "P": 8, "S": 16}

WHITE_SPACE = [
    (0x0009, 0x000D),
    (0x0020, 0x0020),
    (0x0085, 0x0085),
    (0x00A0, 0x00A0),
    (0x1680, 0x1680),
    (0x2000, 0x200A),
    (0x2028, 0x2029),
    (0x202F, 0x202F),
    (0x205F, 0x205F),
    (0x3000, 0x3000),
]


def category_mask(cp: int) -> int:
    cat = unicodedata.category(chr(cp))
    return BIT.get(cat[0], 0)


def build_ranges() -> list[tuple[int, int, int]]:
    ranges = []
    start = None
    prev = 0
    for cp in range(0x110000):
        m = category_mask(cp)
        if m != prev:
            if prev:
                ranges.append((start, cp - 1, prev))
            start = cp if m else None
            prev = m
    if prev:
        ranges.append((start, 0x10FFFF, prev))
    return ranges


def emit(title: str, ranges: list[tuple[int, int, int]], bits: bool) -> str:
    lines = [f"// {title}", "static const UocrUnicodeRange k%s[] = {" % (
        "UnicodeCategoryRanges" if bits else "WhitespaceRanges"), ]
    for lo, hi, m in ranges:
        lines.append(f"    {{0x{lo:06X}u, 0x{hi:06X}u, 0x{m:02X}u}},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "include", "uocr", "unicode_tables.h")

    ranges = build_ranges()
    body = "\n".join(
        [
            "// AUTO-GENERATED by tools/gen_unicode_tables.py -- do not edit.",
            "// Unicode general-category mask ranges (L=1, M=2, N=4, P=8, S=16)",
            "// and Unicode White_Space ranges, from %s." % unicodedata.unidata_version,
            "",
            "#pragma once",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "struct UocrUnicodeRange {",
            "    std::uint32_t lo;",
            "    std::uint32_t hi;",
            "    std::uint8_t mask;",
            "};",
            "",
            emit("general-category mask ranges", ranges, True),
            "",
            "static const UocrUnicodeRange kWhitespaceRanges[] = {",
        ]
    )
    for lo, hi in WHITE_SPACE:
        body += f"\n    {{0x{lo:06X}u, 0x{hi:06X}u, 0x01u}},"
    body += "\n};\n"

    with open(out, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"wrote {out}: {len(ranges)} category ranges, "
          f"{len(WHITE_SPACE)} whitespace ranges")


if __name__ == "__main__":
    main()
